### ISSUE TITLE
After Install No Play Button

### ISSUE THREAD

**Issue by philbritton** [gregjhogan/selenium-grid-hub-site-extension#1]
I can't get the install to properly make the route.  This is what I see after I install.

![image](https://cloud.githubusercontent.com/assets/487081/13585190/5ee51b4c-e488-11e5-914f-f5193ec252d4.png)

When I go to the site I get no route configured.  
https://sitename.scm.azurewebsites.net/grid/console
I also try going to 
https://sitename.azurewebsites.net/grid/console
But nothing there either.

**Comment by gregjhogan** [comment]
That is really strange how it keeps the "+" after installing (I do see this same behavior).  I will look into that.

Did you restart the site in the portal after installing the extension?  Note that the restart button in the SCM site is not sufficient (see [here](https://github.com/projectkudu/kudu/wiki/Azure-Site-Extensions#private-extensions) for more details).

> **Important note:** Site Extensions only get applied after the site is restarted. However, if you modify existing extensions without changing the applicationHost.xdt, no manual restart is needed.
> 
> Also, note that the Restart button on the Site Extension Kudu tab only restarts the scm site (by just killing the process). If your xdt effects the Main site, you will need to either kill the non-Scm w3wp.exe in Kudu's Process Explorer, or fully restart the site from the Azure Portal.

I ask because if I install the site extension into a new web app and hit any of the following URLs they all work:
http://sitename.azurewebsites.net
https://sitename.azurewebsites.net
http://sitename.azurewebsites.net/grid/console
https://sitename.azurewebsites.net/grid/console

**Comment by gregjhogan** [comment]
RE: the play button, as far as I can tell not having a play button is expected when your site extension replaces the site with another process (GoLang site extension is another example).  I looked around and couldn't find any place to configure the play button, if you find something let me know!

![image](https://cloud.githubusercontent.com/assets/4112046/13592554/d691a770-e4b8-11e5-86bf-ebeee08baa79.png)

**Comment by gregjhogan** [comment]
Closing until further info is provided.  Seems likely the web app was not restarted properly after installing.
